openapi: 3.0.0
info:
  title: Toll Interoperability API
  description: API για την ανταλλαγή δεδομένων διοδίων μεταξύ παρόχων.
  version: 1.0.0
servers:
  - url: https://localhost:9115/api
    description: Τοπικός διακομιστής για ανάπτυξη

paths:
  /login:
    post:
      summary: Πραγματοποιεί login και επιστρέφει authentication token.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Επιτυχής αυθεντικοποίηση
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  token:
                    type: string
        "401":
          description: Μη έγκυρα credentials

  /logout:
    post:
      summary: Εκτελεί logout.
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Επιτυχές logout
        "401":
          description: Μη έγκυρο authentication token

  /passAnalysis/stationOpID/{stationOpID}/tagOpID/{tagOpID}/date_from/{from_date}/date_to/{to_date}:
    get:
      summary: Ανάλυση διελεύσεων μεταξύ operators.
      parameters:
        - name: stationOpID
          in: path
          required: true
          schema:
            type: string
        - name: tagOpID
          in: path
          required: true
          schema:
            type: string
        - name: from_date
          in: path
          required: true
          schema:
            type: string
            format: date
        - name: to_date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Επιτυχής ανάκτηση διελεύσεων
          content:
            application/json:
              schema:
                type: object
                properties:
                  stationOpID:
                    type: string
                  tagOpID:
                    type: string
                  nPasses:
                    type: integer
                  passList:
                    type: array
                    items:
                      type: object
                      properties:
                        passID:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
                        stationID:
                          type: string
                        tagID:
                          type: string
                        passCharge:
                          type: number
                          format: float
        "400":
          description: Μη έγκυρη ημερομηνία ή λάθος δεδομένα

  /passesCost/tollOpID/{tollOpID}/tagOpID/{tagOpID}/date_from/{from_date}/date_to/{to_date}:
    get:
      summary: Υπολογισμός κόστους διελεύσεων μεταξύ διοδίων και παρόχων.
      parameters:
        - name: tollOpID
          in: path
          required: true
          schema:
            type: string
        - name: tagOpID
          in: path
          required: true
          schema:
            type: string
        - name: from_date
          in: path
          required: true
          schema:
            type: string
            format: date
        - name: to_date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Επιτυχής επιστροφή κόστους διελεύσεων
          content:
            application/json:
              schema:
                type: object
                properties:
                  tollOpID:
                    type: string
                  tagOpID:
                    type: string
                  nPasses:
                    type: integer
                  passesCost:
                    type: number
                    format: float
        "400":
          description: Μη έγκυρη ημερομηνία ή λάθος δεδομένα

  /admin/tollstations:
    get:
      summary: Λίστα όλων των σταθμών διοδίων.
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Επιτυχής ανάκτηση λίστας διοδίων
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    OpID:
                      type: string
                    Operator:
                      type: string
                    TollID:
                      type: string
                    Name:
                      type: string
                    Locality:
                      type: string

  /admin/resetpasses:
    post:
      summary: Διαγράφει όλες τις διελεύσεις από τη βάση.
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Επιτυχής διαγραφή διελεύσεων
        "401":
          description: Μη έγκυρο authentication token

  /admin/resetstations:
    post:
      summary: Διαγράφει και επανεισάγει τους σταθμούς διοδίων από αρχείο CSV.
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Επιτυχής επαναφορά σταθμών
        "400":
          description: Σφάλμα κατά την εισαγωγή δεδομένων

  /availableDates:
    get:
      summary: Επιστρέφει την πρώτη και τελευταία διαθέσιμη ημερομηνία διελεύσεων.
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Επιτυχής ανάκτηση διαθέσιμων ημερομηνιών
          content:
            application/json:
              schema:
                type: object
                properties:
                  first_date:
                    type: string
                  last_date:
                    type: string
        "404":
          description: Δεν υπάρχουν διαθέσιμες ημερομηνίες

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-OBSERVATORY-AUTH
